version: "3.9"

services:
  backend:
    build:
      context: ./backend 
      dockerfile: dockerfile
    restart: always
 
    ports:
      - "21165:21165"
    depends_on:
      - mongodb 
    environment:
      - DATABASE_url=mongodb://admin:mypass@mongodb:27017
    mem_limit: 256m
    cpus: "0.5" 

  mongodb:
    image: mongo:latest
    restart: always
    ports: 
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=mypass
    volumes:
      - mongo_data:/data/db
    mem_limit: 256m
    cpus: "0.5"

volumes: 
  mongo_data:
