FROM node:22.20.0-slim
WORKDIR /app

COPY pnpm-lock.yaml ./
COPY package.json ./

RUN apt-get update && apt-get install -y git netcat-openbsd

RUN npm install -g pnpm \
    && pnpm install --frozen-lockfile

COPY . . 

EXPOSE 2165

CMD ["pnpm", "start"]
